### ISSUE TITLE
Unable to start a node with gs_startnode MacOS

### ISSUE THREAD

**Issue by jjoek** [griddb/c_client#36]
Just installed GridDb, already configured and everything worked fine except for an error:
```
checking whether FALLOC_FL_PUNCH_HOLE is declared... no
configure: error: fallocate and FALLOC_FL_PUNCH_HOLE must be supported
```
Which I skipped through, I was able to add user and actually even change the admin password with `gs_adduser` and `gs_passwd` but upon running `gs_startnode`, I get the error below and thus unable to proceed. 

```
Traceback (most recent call last):
  File "/Users/jjoek/griddb/bin/gs_startnode", line 122, in <module>
    proc = subprocess.Popen(command, stdout=f, stderr=f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I am on a macos,
running python 2.7 but also have python3 installed.

Asked the question on stackoverflow here [https://stackoverflow.com/questions/70299642/unable-to-start-a-node-with-gs-startnode-macos](https://stackoverflow.com/questions/70299642/unable-to-start-a-node-with-gs-startnode-macos)

**Comment by knonomura** [comment]
Thank you for question. 
Unfortunately GridDB Server doesn’t support MacOS as of now. 
Currently the following linux distributions are supported (CentOS, Ubuntu, openSUSE).
Could you please use GridDB C Client library with GridDB Server on Linux ?
